#! /bin/sh

set -eu

export GOBIN=$PWD/bin
export PATH=$GOBIN:$PATH

go install ./vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go install ./vendor/github.com/golang/protobuf/protoc-gen-go

go generate ./...