#!/usr/bin/env bash

set -e
rm c.out || true
touch c.out

for d in $(go list ./... | grep -v vendor | grep -v cmd/phraser); do
    echo $d
    go test -v -coverprofile=cover.out $d
    if [ -f cover.out ]; then
        cat cover.out >> c.out
        rm cover.out
    fi
done
