#!/usr/bin/env bash

set -e
echo "" > coverage.txt

for d in $(go list ./... | grep -v vendor); do
    echo $d
    go test -v -race -coverprofile=c.out -covermode=atomic $d
    if [ -f c.out ]; then
        cat c.out >> coverage.txt
        rm c.out
    fi
done
